# Generated by Django 4.2.13 on 2024-07-01 02:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="birth_date",
            field=models.DateField(),
        ),
    ]
