# Generated by Django 5.2.4 on 2025-08-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='assistant_teachers',
            field=models.ManyToManyField(related_name='assistant_courses', to='teachers.teacher'),
        ),
    ]
