# Generated by Django 5.2.4 on 2024-07-08 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_genre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genre",
            name="books",
        ),
        migrations.AddField(
            model_name="book",
            name="genre",
            field=models.ManyToManyField(related_name="books", to="books.genre"),
        ),
    ]
